site_name: Bootcamp - Engenharia de Dados

theme:
  name: material

nav:
  - Início: index.md
  - Contratos de dados:
      - Input Schemas: input-schemas.md
      - Output Schemas: output-schemas.md
  - Funções:
      - Config: config.md
      - Extract: extract.md
      - Transform: transform.md
      - Load: load.md

plugins:
  - search
  - mermaid2
  - mkdocstrings